# Generated by Django 5.0 on 2025-11-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone',
        ),
    ]
